BMotionReporting/Controllers/FuelController.cs
using BMotionReporting.App_Start;
using BMotionReporting.Entity;
using BMotionReporting.Logic;
using BMotionReporting.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BMotionReporting.Controllers
{
    public class FuelController : Controller
    {
        // GET: Fuel
        BMotionDBEntities db = new BMotionDBEntities();

        [CheckAuthorizeAttribute()]
        public ActionResult Index()
        {
            List<Entity.Fuel> fuel = FuelLogic.getInstance().getAllFuel();
            List<FuelModels> Data = new List<FuelModels>();
            for(int i = 0; i < fuel.Count; i++)
            {
                FuelModels item = new FuelModels();
                item.FuelId = fuel[i].FuilId;
                item.FuelName = fuel[i].Name;
                item.Price = fuel[i].Price;
                item.IsSubsidy = fuel[i].IsSubsidy == "Y"?"Subsidi":"Non Subsidi";
                item.BackgroundColor = fuel[i].BackgroundColor;
                item.TextColor = fuel[i].TextColor;
                item.CreatedDate = fuel[i].CreatedDate;
                item.CreatedBy = fuel[i].CreatedBy;
                item.UpdatedDate = fuel[i].UpdatedDate;
                item.UpdatedBy = fuel[i].UpdatedBy;

                Data.Add(item);
            }
            PagedList<FuelModels> page = new PagedList<FuelModels>();
            page.Content = Data;
            return View(page);
        }

        [CheckAuthorizeAttribute()]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(FuelModels model)
        {
            try
            {
                if (FuelLogic.getInstance().CheckExistingData(model))
                {
                    FuelLogic.getInstance().Add(model);
                    TempData["Success"] = "Success saving Data for " + model.FuelName;
                }
                else
                {
                    TempData["Error"] = "User " + model.FuelName + " is exist";
                }
            }
            catch (Exception e)
            {
                Logging.Log.getInstance().CreateLogError(e);
            }

            return RedirectToAction("Index");
        }

        [CheckAuthorizeAttribute()]
        public ActionResult Edit(int ID)
        {
            FuelModels model = new FuelModels();
            var data = db.Fuels.Where(f => f.FuilId == ID).ToList();
            if(data.Count() > 0)
            {
                model.FuelId = data.FirstOrDefault().FuilId;
                model.FuelName = data.FirstOrDefault().Name;
                model.Price = data.FirstOrDefault().Price;
                model.IsSubsidy = data.FirstOrDefault().IsSubsidy;
                model.BackgroundColor = data.FirstOrDefault().BackgroundColor;
                model.TextColor = data.FirstOrDefault().TextColor;
                model.CreatedDate = data.FirstOrDefault().CreatedDate;
                model.CreatedBy = data.FirstOrDefault().CreatedBy;
                model.UpdatedDate = data.FirstOrDefault().UpdatedDate;
                model.UpdatedBy = data.FirstOrDefault().UpdatedBy;
            }
            else
            {

            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(FuelModels model)
        {
            try
            {
                FuelLogic.getInstance().Update(model);
                TempData["Success"] = "Success saving Data for " + model.FuelName;
            }
            catch (Exception e)
            {
                Logging.Log.getInstance().CreateLogError(e);
            }

            return RedirectToAction("Index");
        }

        //[HttpPost]
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            FuelLogic.getInstance().Remove(id);
            TempData["Success"] = "Delete Success";
            return RedirectToAction("Index");
        }
    }
}

BMotionReporting/Controllers/InfoController.cs
using BMotionReporting.App_Start;
using BMotionReporting.Entity;
using BMotionReporting.Logic;
using BMotionReporting.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BMotionReporting.Controllers
{
    public class InfoController : Controller
    {
        BMotionDBEntities db = new BMotionDBEntities();
        // GET: Info
        [CheckAuthorizeAttribute()]
        public ActionResult Index()
        {
            //InfoLogic.SendNotificationFromFirebaseCloud();
            List<sp_Notification_Result> Notif = InfoLogic.getInstance().getAllInfo();
            PagedList<sp_Notification_Result> page = new PagedList<sp_Notification_Result>();
            page.Content = Notif;
            return View(page);
        }

        [CheckAuthorizeAttribute()]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(sp_Notification_Result model)
        {
            try
            {
                InfoLogic.getInstance().Add(model);
                TempData["Success"] = "Info " + model.Title + " telah dipublikasikan.";
            }
            catch (Exception e)
            {
                Logging.Log.getInstance().CreateLogError(e);
            }

            return RedirectToAction("Index");
        }
    }
}

BMotionReporting/Controllers/OrdersController.cs
using AForge.Video.DirectShow;
using BMotionReporting.App_Start;
using BMotionReporting.Entity;
using BMotionReporting.Logic;
using BMotionReporting.Models;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace BMotionReporting.Controllers
{
    public class OrdersController : Controller
    {
        BMotionDBEntities db = new BMotionDBEntities();
        // GET: Orders
        [CheckAuthorizeAttribute()]
        public ActionResult Index()
        {
           return View();
        }

        [CheckAuthorizeAttribute()]
        public ActionResult Activity()
        {
            var page = new PagedList<sp_OrderMonitoring_Result>();
            try
            {
                var model = OrdersLogic.getInstance().GetAllActivity().ToList();
                page.Content = model;
            }
            catch (Exception e)
            {
                Logging.Log.getInstance().CreateLogError(e);
            }
            return View(page);
        }

        [CheckAuthorizeAttribute()]
        public ActionResult History()
        {
            var page = new PagedList<sp_RiwayatPengambilanBBM_Result>();
            try
            {
                var model = OrdersLogic.getInstance().GetAllHistory().ToList();
                page.Content = model;
            }
            catch (Exception e)
            {
                Logging.Log.getInstance().CreateLogError(e);
            }
            return View(page);
        }

        [HttpPost]
        public ActionResult StrukBBM(string orderNo)
        {
            StruckModels struk = new StruckModels();
            //StruckOrderDetails orderDetail = new StruckOrderDetails();
            FuelModels fuelModels = new FuelModels();
            List<StruckModels> listModel = new List<StruckModels>();
            List<StruckOrderDetails> listOrder = new List<StruckOrderDetails>();
            List<FuelModels> fuelList = new List<FuelModels>();
            try
            {
                int n;
                bool isNumeric = int.TryParse(orderNo, out n);
                var list = db.sp_StrukPengambilanBBM(orderNo).ToList();
                if (isNumeric)
                {
                    // Confirmation Struck
                    if (db.OrderDetails.AsEnumerable().Where(dtl => dtl.OrderDetailId == Int32.Parse(orderNo) && dtl.IsVerify == null).Count() > 0)
                    {
                        //OrderDetails model = new OrderDetails();
                        //model.OrderDetailId = Convert.ToInt32(orderNo);
                        //OrdersLogic.getInstance().VerifyOrder(model);
                        
                        var verify = db.sp_OrderDetailVerify(orderNo);
                        return Json("OK", JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json("Failed", JsonRequestBehavior.AllowGet);
                    }
                }
                // Get Struk
                else if (list.Count > 0)
                {
                    foreach (var item in list)
                    {
                        struk = new StruckModels();
                        struk.OrderNo = item.OrderNo;
                        struk.OutletNo = item.OutletNo;
                        struk.OutletName = item.OutletName;
                        struk.Name = item.Name;

                        struk.FuelName = item.FuelName;
                        struk.Liter = item.Liter;
                        struk.OrderDetailId = item.OrderDetailId;
                        struk.CreatedDate = item.CreatedDate.Value.ToString("MM/dd/yyyy HH:mm:ss");
                        listModel.Add(struk);
                    }

                }
                else
                {
                    return Json("Failed", JsonRequestBehavior.AllowGet);
                }

            } 
            catch (Exception e)
            {
                Logging.Log.getInstance().CreateLogError(e);
            }

            return Json(listModel, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult OrderFuel(string NIP)
        {
            try
            {
                NewOrder order = new Models.NewOrder();
                if (db.Users.Where(u => u.NIP.Equals(NIP)).Count() != 0)
                {
                    var user = UserLogic.getInstance().GetUserById(NIP);
                    if (user.IsVerify.ToLower() == "y")
                    {

                        var quota = db.sp_UserQuota(NIP).FirstOrDefault();
                        order.NIP = user.NIP;
                        order.Nama = user.Name;
                        order.Phone = user.Telp;
                        order.Email = user.Email;
                        order.Quota = quota.Quota;

                        FuelOrder fuel = new FuelOrder();
                        List<FuelItemOrder> subsidi = new List<FuelItemOrder>();
                        List<FuelItemOrder> nonSubsidi = new List<FuelItemOrder>();

                        List<Fuel> fuelList = FuelLogic.getInstance().getAllFuel();
                        for (int i = 0; i < fuelList.Count; i++)
                        {
                            FuelItemOrder item = new FuelItemOrder();

                            item.FuelId = fuelList[i].FuilId.ToString();
                            item.Fuel = fuelList[i].Name;

                            if (fuelList[i].IsSubsidy.ToLower() == "y")
                            {
                                subsidi.Add(item);
                            }
                            else
                            {
                                nonSubsidi.Add(item);
                            }
                        }

                        fuel.Subsidi = subsidi;
                        fuel.NonSubsidi = nonSubsidi;

                        order.Fuel = fuel;

                        return Json(order, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json("Failed", JsonRequestBehavior.AllowGet);
                    }
                }
                else {
                    return Json("Failed", JsonRequestBehavior.AllowGet);
                }
                //OrderDetails detail = new OrderDetails();
                //Orders orderDetails = new Orders();

                //List<OrderDetails> listDetail = new List<OrderDetails>();
                
                //if (arrValue != null)
                //{
                //    string[] arrNIP = arrValue[0].Split(',');
                //    string[] arrFuelId = arrValue[1].Split(',');
                //    string[] arrLiter = arrValue[2].Split(',');

                //    if (order.NIP == null)
                //    {
                //        order = new Models.Orders();
                //        order.NIP = arrNIP[0];
                //    }

                //    for (int i = 0; i < arrFuelId.Length; i++)
                //    {
                //        detail = new OrderDetails();
                //        detail.FuelId = Convert.ToInt32(arrFuelId[i]);
                //        detail.Liter = Convert.ToInt32(arrLiter[i]);
                //        listDetail.Add(detail);
                //    }

                //    order.OrderDetails = listDetail;
                //    orderDetails = OrdersLogic.getInstance().Add(order);
                //}

                //return Json(orderDetails, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Logging.Log.getInstance().CreateLogError(e);
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult OrderAdd(OrderParameter param)
        {
            try
            {
                return Json(OrdersLogic.getInstance().Add(param), JsonRequestBehavior.AllowGet);
                
            }
            catch (Exception e)
            {
                Logging.Log.getInstance().CreateLogError(e);
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [CheckAuthorizeAttribute()]
        public ActionResult ExportToExcel()
        {
            try
            {
                ExcelPackage Package = new ExcelPackage();
                ExcelWorksheet ws = Package.Workbook.Worksheets.Add("Data");
                Color colFromHex = System.Drawing.ColorTranslator.FromHtml("#00b0f0");
                OfficeOpenXml.Style.ExcelBorderStyle DefaultBorder = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

                ws.Cells["A1"].LoadFromText("No");
                ws.Cells["A1"].Style.Font.SetFromFont(new Font("Cambria", 10));
                ws.Cells["A1"].Style.Font.Color.SetColor(Color.White);
                ws.Cells["A1"].Style.Font.Bold = true;
                ws.Cells["A1"].Style.Fill.PatternType = ExcelFillStyle.Solid;
                ws.Cells["A1"].Style.Fill.BackgroundColor.SetColor(colFromHex);
                ws.Cells["A1"].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                ws.Cells["A1"].Style.VerticalAlignment = OfficeOpenXml.Style.ExcelVerticalAlignment.Center;
                ws.Cells["A1"].Style.Border.Bottom.Style = DefaultBorder;
                ws.Cells["A1"].Style.Border.Left.Style = DefaultBorder;
                ws.Cells["A1"].Style.Border.Top.Style = DefaultBorder;
                ws.Cells["A1"].Style.Border.Right.Style = DefaultBorder;

                ws.Cells["B1"].LoadFromText("Tanggal Transaksi");
                ws.Cells["B1"].Style.Font.SetFromFont(new Font("Cambria", 10));

BMotionReporting/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>BMotion Reporting</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">
    <!-- Bootstrap core CSS -->
    <link href="~/Content/AdminLTE/all.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE/daterangepicker.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE/bootstrap-colorpicker.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE/responsive.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE/adminlte.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/CSS/layout.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    @RenderSection("scripts", required: false)

    <script src="~/Scripts/AdminLTE/jquery.min.js"></script>
    <script src="~/Scripts/JS/qrcode.min.js"></script>
    <script src="~/Scripts/JS/instascan.min.js"></script>
    <script src="~/Scripts/AdminLTE/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/AdminLTE/moment.min.js"></script>
    <script src="~/Scripts/AdminLTE/jquery.inputmask.bundle.min.js"></script>
    <script src="~/Scripts/AdminLTE/daterangepicker.js"></script>
    <script src="~/Scripts/AdminLTE/bootstrap-colorpicker.min.js"></script>
    <script src="~/Scripts/AdminLTE/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/Scripts/AdminLTE/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/AdminLTE/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/AdminLTE/dataTables.responsive.min.js"></script>
    <script src="~/Scripts/AdminLTE/responsive.bootstrap4.min.js"></script>
    <script src="~/Scripts/AdminLTE/adminlte.js"></script>
    <script src="~/Scripts/bootstrap.bundle.js"></script>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        .container {
            width: auto;
            max-width: 680px;
            padding: 0 15px;
        }

        .footer {
            background-color: #f5f5f5;
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="~/Content/CSS/dashboard.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow" style="background-color:#195396 !important">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3 text-center"  href="@Url.Action("Index","Home")">
            <img src="~/Assets/logo-white.png" style="width:100px" />
        </a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @*<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">*@
        @*<ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">Keluar</a>
            </li>
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">Keluar</a>
            </li>
        </ul>*@
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse" style="overflow-y:hidden">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item" style="margin:10px;">
                            <a class="nav-link" href="@Url.Action("Index","Home")">
                                <img src="~/Assets/icon_home.png" width="20" height="20" />
                                <span data-feather="home" style="padding:5px"></span>
                                Home
                            </a>
                        </li>
                        <li class="nav-item" style="margin:10px;">
                            <a class="nav-link" href="@Url.Action("Index","UserAdmin")">
                                <img src="~/Assets/icon_admin.png" width="20" height="20" />
                                <span data-feather="home" style="padding:5px"></span>
                                User Administrator
                            </a>
                        </li>
                        <li class="nav-item" style="margin:10px;">
                            <a class="nav-link" href="@Url.Action("Index","Fuel")">
                                <img src="~/Assets/icon_fuel.png" width="20" height="20" />
                                <span data-feather="home" style="padding:5px"></span>
                                Fuel
                            </a>
                        </li>
                        <li class="nav-item" style="margin:10px;">
                            <a class="nav-link" href="@Url.Action("Index","Users")">
                                <img src="~/Assets/icon_daftar_pengguna.png" width="20" height="20" />
                                <span data-feather="file" style="padding:5px"></span>
                                Daftar Pengguna
                            </a>
                        </li>
                        <li class="nav-item" style="margin:10px;">
                            <a class="nav-link" href="@Url.Action("Index","Orders")">
                                <img src="~/Assets/icon_pengambilan_bbm.png" width="20" height="20" />
                                <span data-feather="shopping-cart" style="padding:5px"></span>
                                Pengambilan BBM
                            </a>
                        </li>
                        <li class="nav-item" style="margin:10px;">
                            <a class="nav-link" href="@Url.Action("Activity","Orders")">
                                <img src="~/Assets/icon_order.png" width="20" height="20" />
                                <span data-feather="shopping-cart" style="padding:5px"></span>
                                Order Monitoring
                            </a>
                        </li>
                        <li class="nav-item" style="margin:10px;">
                            <a class="nav-link" href="@Url.Action("History","Orders")">
                                <img src="~/Assets/icon_riwayat_pengambilan_bbm.png" width="20" height="20" />
                                <span data-feather="bar-chart-2" style="padding:5px"></span>
                                Riwayat Pengambilan BBM
                            </a>
                        </li>
                        <li class="nav-item" style="margin:10px;">
                            <a class="nav-link" href="@Url.Action("Index","Info")">
                                <img src="~/Assets/icon_info.png" width="20" height="20" />
                                <span data-feather="bar-chart-2" style="padding:5px"></span>
                                Info
                            </a>
                        </li>
                        <li class="nav-item" style="margin:10px;">
                            <a class="nav-link" href="@Url.Action("Index","Feedback")">
                                <img src="~/Assets/icon_notifikasi.png" width="30" height="30" />
                                <span data-feather="users" style="padding:5px"></span>
                                Kritik & Saran
                            </a>
                        </li>
                    </ul>
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <a class="nav-link" href="@Url.Action("Logout","Account")">
                            <img src="~/Assets/icon_keluar.png" width="20" height="20" />
                            <span data-feather="bar-chart-2" style="padding:5px"></span>
                            Keluar
                        </a>
                    </h6>

                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 page-background">
                <div style="margin:5%">
                    @RenderBody()
                </div>
                
                @*<footer class="footer mt-auto py-3">
                    <div class="container">
                        <span class="text-muted">&copy;@DateTime.Now.Year - BMotion Reporting</span>
                    </div>
                </footer>*@ 
            </main>        
        </div>
    </div>
</body>
</html>